### ISSUE TITLE
Serverless下如何让next.js支持增量静态再生

### ISSUE THREAD

**Issue by JOU-amjs** [serverless-plus/serverless-cnode#11]
我们的网站是用next.js开发的，为了让网页更快响应我们使用了next.js的页面静态化功能，现在碰到两个这样的问题
1. 我们的首页是需要定期更新的，因此使用了next.js的revalidate来定期重新更新缓存文件
2. 我们的子页面有很多，几百上千个，因此我们使用了等到访问再生成页面缓存文件的策略

但查看后云函数的代码部署位置不支持文件的写入，导致上面这些都无效了。请问有什么方案可以解决这样的问题吗？

**Comment by yugasun** [comment]
@JOU-amjs 持久化静态渲染缓存可以使用多种方式，比如：
1. 高频渲染缓存放到 Redis 中
2. 低频缓存上传到 [COS](https://console.cloud.tencent.com/cos)，使用时下载，成本低，同地域云函数与cos应该延迟很低
3. 云函数挂在 [CFS](https://console.cloud.tencent.com/cfs)，这样可以直接在云函数内写入缓存文件到 CFS 挂在目录，参考：https://cloud.tencent.com/document/product/582/47148
